language: python

python:
        - '3.8'
        
install:
        - pip install -r requirements.txt

script:
        - echo 'Run basic test'
        - python manage.py test -v 2
        - echo 'Run NLP test'
        - python manage.py test nlp
