language: python

branches:
  only:
    - master

python:
        - '3.8'
        
install:
        - pip install en-core-web-sm==2.3.0
        - pip install -r requirements.txt
        
script:
        - echo 'Make migrations'
        - python manage.py make migrations
        - echo 'Migrate'
        - python manage.py migrate
