language: python

branches:
  only:
    - master

python:
        - '3.7.4'
        
install:
        - pip install spacy==2.3.5    
        - pip install https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-2.3.0/en_core_web_sm-2.3.0.tar.gz
        - pip install -r requirements.txt
        
script:
        - echo 'Make migrations'
        - python manage.py makemigrations
        - echo 'Migrate'
        - python manage.py migrate
