language: python

branches:
  only:
    - basic-platform-cicd

python:
        - '3.8'
        
install:
        - pip install -r requirements.txt
        - pip install Django
        - pip install django-ckeditor
        - pip install Pillow

script:
        - echo 'Run basic test'
        - python manage.py test -v 2
