language: python

branches:
  only:
    - master

python:
        - '3.7.4'
        
install:
        - pip install pip==19.0.3
        - pip --version
        - pip3 --version
        - pip3 install en-core-web-sm==2.3.0
        - pip3 install -r requirements.txt
        
script:
        - echo 'Make migrations'
        - python manage.py make migrations
        - echo 'Migrate'
        - python manage.py migrate
